### ISSUE TITLE
Some Non-Sticky collectionView cell's text is getting bold

### ISSUE THREAD

**Issue by inertialelements** [V8tr/CollectionViewGridLayout-Final#5]
Set the font of sticky header cell to bold using  _gridLayout.isItemSticky(at: indexPath)_  condition but I found that some non-sticky cell is getting bold. How can I resolved this issue?

For more clarification, please check the screenshot.
![StickyGridCollectionView](https://user-images.githubusercontent.com/36266217/69872362-397f4000-12db-11ea-87a8-92624de4ab77.png)

**Comment by ajitgupta123** [comment]
I also faced same issue. You have to set the font of non-sticky's cell. e.g.
if  gridLayout.isItemSticky(at: indexPath) {
  cell.text_label.font = UIFont(......)  // Bold text
}else{
   cell.text_label.font = UIFont(......)  // Regular text
}

It will resolve your problem.

**Comment by inertialelements** [comment]
Thanks Ajit.
